name: Test

on:
  pull_request_target:
    branches: [master]

jobs:
  buildAndDownload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Make CLI version
        run: |
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -B build -S .
          cmake --build build

      - name: Download latest GCLC release
        run: |
          mkdir latest
          cd latest
          wget https://github.com/janicicpredrag/gclc/releases/latest/download/linux.zip
          unzip linux.zip gclc
          chmod +x gclc

      - name: Move files
        run: |
          mkdir testFiles/
          mv build/gclc testFiles/gclc-pr
          mv latest/gclc testFiles/gclc-latest
          mv test/* testFiles/
          mv samples testFiles/

      - name: Upload test files
        uses: actions/upload-artifact@v4
        with:
          name: testFiles
          path: testFiles/

  outputTests:
    runs-on: ubuntu-latest
    steps:
      - name: Download test files
        uses: actions/download-artifact@v4
        with:
          name: testFiles

      - name: Run tests
        run: |
          ./compare_outputs.sh gclc-latest gclc-pr samples/basic_samples/
          cat diff-log >> $GITHUB_STEP_SUMMARY

  proofTests:
    runs-on: ubuntu-latest
    steps:
      - name: Download test files
        uses: actions/download-artifact@v4
        with:
          name: testFiles

      - name: Run tests
        run: |
          ./compare_proofs.sh gclc-latest gclc-pr samples/samples_prover/
          cat proof-log >> $GITHUB_STEP_SUMMARY
